version: 2.1

# commands:
#   destroy_environment:
#     steps:
#       - run:
#           name: "Delete AWS stack for rollback"
#           command: |
#             aws cloudformation delete-stack \
#               --stack-name my-stack

jobs:
  create_infra:
    docker:
      - image: amazon/aws-cli
      #- image: cimg/base:2020.01
    steps:
      - checkout
      ## - add_ssh_keys:
      #     fingerprints:
      #       - "84:a9:8b:d6:e9:68:1b:78:80:e0:4e:22:a3:0a:30:00"  #
      - run:
          name: "Create an AWS stack"
          command: |
            # pwd
            # ls -ltra
            yum update -y
            #yum install git
            #yum install ssh
            aws cloudformation deploy --template-file template.yml --stack-name my-stack --region us-west-1
            #return 1
      #- destroy_environment
      - run:
          name: "Delete AWS stack for rollback"
          command: |
            aws cloudformation delete-stack \
              --stack-name my-stack
          when: on_fail

workflows:
  myworkflow:
    jobs:
      - create_infra
          # requires:
          #   - destroy_environement